version: '3.7'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./:/go/app
    command: air
    ports:
      - 8888:8888
      - 2345:2345
      - 3000:3000 
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
